In [2]:
import pandas as pd

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-02-car-price/data.csv

--2026-09-24 18:25:33--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.007s

2026-09-24 18:25:33 (215 MB/s) - ‘data.csv’ saved [1475504/1475504]

In [4]:
df = pd.read_csv("data.csv")

In [5]:
df.count

<bound method DataFrame.count of           Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0
1          BMW    1 Series  2011     premium unleaded (required)      300.0
2          BMW    1 Series  2011     premium unleaded (required)      300.0
3          BMW    1 Series  2011     premium unleaded (required)      230.0
4          BMW    1 Series  2011     premium unleaded (required)      230.0
...        ...         ...   ...                             ...        ...
11909    Acura         ZDX  2012     premium unleaded (required)      300.0
11910    Acura         ZDX  2012     premium unleaded (required)      300.0
11911    Acura         ZDX  2012     premium unleaded (required)      300.0
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0
11913  Lincoln      Zephyr  2006                regular unleaded      221.0

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0
1                   6.0            MANUAL   rear wheel drive              2.0
2                   6.0            MANUAL   rear wheel drive              2.0
3                   6.0            MANUAL   rear wheel drive              2.0
4                   6.0            MANUAL   rear wheel drive              2.0
...                 ...               ...                ...              ...
11909               6.0         AUTOMATIC    all wheel drive              4.0
11910               6.0         AUTOMATIC    all wheel drive              4.0
11911               6.0         AUTOMATIC    all wheel drive              4.0
11912               6.0         AUTOMATIC    all wheel drive              4.0
11913               6.0         AUTOMATIC  front wheel drive              4.0

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe
1                         Luxury,Performance      Compact    Convertible
2                    Luxury,High-Performance      Compact          Coupe
3                         Luxury,Performance      Compact          Coupe
4                                     Luxury      Compact    Convertible
...                                      ...          ...            ...
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11913                                 Luxury      Midsize          Sedan

       highway MPG  city mpg  Popularity   MSRP
0               26        19        3916  46135
1               28        19        3916  40650
2               28        20        3916  36350
3               28        18        3916  29450
4               28        18        3916  34500
...            ...       ...         ...    ...
11909           23        16         204  46120
11910           23        16         204  56670
11911           23        16         204  50620
11912           23        16         204  50920
11913           26        17          61  28995

[11914 rows x 16 columns]>

In [2]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]=10

In [8]:
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [17]:
n[1,0]

np.int64(4)

In [19]:
n[2]=[1,1,1]

In [20]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [21]:
n[:,1]

array([2, 5, 1])

In [25]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [27]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [29]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
b=(10+(a*2)) ** 2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a/b+10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [33]:
a >= 2

array([False, False,  True,  True,  True])

In [34]:
a > b

array([False, False,  True,  True,  True])

In [35]:
a[a>b]

array([2, 3, 4])

In [36]:
a.min()

np.int64(0)

In [37]:
b.max()

np.float64(3.24)

In [38]:
a.sum()

np.int64(10)

In [39]:
a.mean()

np.float64(2.0)

In [40]:
a.std()

np.float64(1.4142135623730951)

In [41]:
n.sum()

np.int64(24)

In [42]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [4]:
u=np.array([2,4,5,6])
v=np.array([1,0,0,2])

In [5]:
u*v

array([ 2,  0,  0, 12])

In [10]:
u.shape[0]

4

In [20]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [12]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [13]:
u.dot(v)

np.int64(14)

In [14]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]])
v=np.array([1,0.5,2,1])

In [15]:
u.dot(v)

array([20. ,  6. ,  8.5])

In [22]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result

In [23]:
matrix_vector_multiplication(u,v)

array([20. ,  6. ,  8.5])

In [26]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_columns = V.shape[1]
    result = np.zeros((num_rows, num_columns))
    for i in range(num_columns):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result

In [30]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]])
v = np.array([
    [2,4,5],
    [1,2,1],
    [3,1,2],
    [6,2,1]])
matrix_matrix_multiplication(u,v)

array([[59, 33, 30],
       [19, 13, 11],
       [19, 18, 21]])

In [31]:
u.dot(v)

array([[59, 33, 30],
       [19, 13, 11],
       [19, 18, 21]])

In [34]:
I = np.eye(3)

In [36]:
v.dot(I)

array([[2., 4., 5.],
       [1., 2., 1.],
       [3., 1., 2.],
       [6., 2., 1.]])

In [39]:
vs = v[[0,1,2]]
vs

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [41]:
vs_inv = np.linalg.inv(vs)
vs_inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [42]:
vs.dot(vs_inv)

array([[ 1.00000000e+00,  3.33066907e-16,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [1]:
import pandas as pd

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [47]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    # ...
]

In [48]:
pd.DataFrame(data)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [49]:
pd.__version__

'3.0.6'

In [4]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
df.loc[[1,2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [9]:
df.iloc[[1,2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990